import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AmountInput } from '../components/AmountInput'
import { Modal } from '../components/Modal'
import { Page } from '../components/Page'
import { ProgressTrack } from '../components/ProgressTrack'
import { impulseImpact } from '../financial-engine'
import { useFinance } from '../hooks/useFinance'
import { db } from '../storage/db'
import type { Debt } from '../types/models'
import { formatARS, formatDate, id, todayISO } from '../utils/format'

export function Dashboard(){const f=useFinance(),[modal,setModal]=useState<'impulse'|'support'|'payment'|'explain'|null>(null);const [amount,setAmount]=useState(0),[purchase,setPurchase]=useState(''),[decision,setDecision]=useState<'saved'|'bought'|null>(null),[paymentDebt,setPaymentDebt]=useState(f.debts[0]?.id??'');const next=useMemo(()=>[...f.debts].filter(d=>d.balance>0).sort((a,b)=>(a.dueDate??'9999').localeCompare(b.dueDate??'9999')),[f.debts]);const impact=impulseImpact(amount,f.debts,f.budget.availableExtra,f.settings.strategy)
  useEffect(()=>{if(!paymentDebt&&f.debts.length)setPaymentDebt(f.debts[0].id)},[paymentDebt,f.debts])
  const registerPayment=async()=>{const debt=f.debts.find(d=>d.id===paymentDebt);if(!debt||amount<=0)return;const paid=Math.min(amount,debt.balance);await db.transaction('rw',db.debts,db.payments,async()=>{await db.payments.add({id:id(),debtId:debt.id,amount:paid,date:todayISO()});await db.debts.put({...debt,balance:Math.max(0,debt.balance-paid)})});setAmount(0);setModal(null)}
  if(!f.debts.length&&!f.settings.onboardingComplete)return <Page title="Primero veamos dónde estás" eyebrow="Tu plan"><div className="empty large"><span>🧭</span><h2>Todavía no cargaste tu situación.</h2><p>Son pasos cortos y todo queda guardado en este dispositivo.</p><Link className="button primary" to="/empezar">Empezar</Link></div></Page>
  return <Page title="Tu plan" eyebrow="Hoy" action={<button className="button secondary small" onClick={()=>{setAmount(0);setModal('payment')}}>+ Registrar pago</button>}><p className="support-line">{f.progress.paid>0?'Todavía falta, pero ya no estás donde empezaste.':'Ahora que los números están juntos, podemos ir de a una.'}</p>{f.budget.deficit>0?<Crisis deficit={f.budget.deficit} debts={next}/>:<><div className="metric-grid"><article className="metric hero-metric"><small>Saldo pendiente</small><strong>{formatARS(f.progress.remaining)}</strong><span>en {f.debts.filter(d=>d.balance>0).length} deudas</span></article><article className="metric"><small>Próximo objetivo</small><strong>{next[0]?formatARS(Math.min(next[0].balance,Math.max(next[0].minimumPayment,next[0].agreedPayment??0))):'$ 0'}</strong><span>{next[0]?.dueDate?`antes del ${formatDate(next[0].dueDate)}`:'sin vencimiento cargado'}</span></article><article className="metric"><small>Podés adelantar</small><strong>{formatARS(f.budget.availableExtra)}</strong><span>después de mínimos</span></article><article className="metric"><small>A este ritmo</small><strong>{f.projection.completionDate?formatDate(f.projection.completionDate):'A revisar'}</strong><span>{f.projection.approximate?'estimación sin todas las tasas':'según la estrategia elegida'}</span></article></div><button className="calculation-link" onClick={()=>setModal('explain')}>¿Cómo calculamos esto?</button><ProgressTrack percent={f.progress.percent} character={f.settings.progressCharacter} paid={f.progress.paid} remaining={f.progress.remaining}/></>}
  <section className="section-card"><div className="section-title"><div><p className="eyebrow">Calendario</p><h2>Lo próximo</h2></div><Link to="/deudas">Ver deudas</Link></div>{next.length?next.slice(0,4).map(d=><div className="obligation" key={d.id}><span><strong>{d.name}</strong><small>{formatDate(d.dueDate)}</small></span><strong>{formatARS(Math.min(d.balance,Math.max(d.minimumPayment,d.agreedPayment??0)))}</strong></div>):<div className="empty">No quedan deudas pendientes.</div>}</section>
  <div className="tool-grid"><button className="tool-card" onClick={()=>{setAmount(0);setDecision(null);setModal('impulse')}}><span>🛒</span><h3>Estoy por gastar en una boludez</h3><p>Veamos qué significa para tu plan.</p></button><button className="tool-card" onClick={()=>setModal('support')}><span>❤️</span><h3>Siento que no voy a salir más</h3><p>Miremos el próximo paso, no todo junto.</p></button></div>
  {modal==='payment'&&<Modal title="Registrar un pago" onClose={()=>setModal(null)}><label className="field"><span>¿A qué deuda?</span><select value={paymentDebt} onChange={e=>setPaymentDebt(e.target.value)}>{f.debts.filter(d=>d.balance>0).map(d=><option key={d.id} value={d.id}>{d.name} · {formatARS(d.balance)}</option>)}</select></label><label className="field"><span>¿Cuánto pagaste?</span><AmountInput value={amount||''} onChange={setAmount}/></label><p className="help">Solo registralo cuando el pago realmente se haya hecho.</p><div className="modal-actions"><button className="button ghost" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={!amount||!paymentDebt} onClick={registerPayment}>Guardar pago</button></div></Modal>}
  {modal==='impulse'&&<Modal title="Veamos qué significa" onClose={()=>setModal(null)}>{decision?<div className="decision-result"><span>{decision==='saved'?'🌱':'👌'}</span><p>{decision==='saved'?'Bien ahí. Sumalo cuando realmente lo hayas reservado o pagado.':'Dale. Lo importante era decidir sabiendo qué significaba. Seguimos con el plan.'}</p><button className="button primary" onClick={()=>setModal(null)}>Volver al plan</button></div>:<><p>No te voy a decir qué hacer. Pongámoslo en contexto.</p><label className="field"><span>¿Cuánto cuesta?</span><AmountInput value={amount||''} onChange={setAmount}/></label><label className="field"><span>¿Qué querés comprar? <small>(opcional)</small></span><input value={purchase} onChange={e=>setPurchase(e.target.value)} placeholder="Por ejemplo, unas zapatillas"/></label>{amount>0&&<div className="impact-box"><strong>{formatARS(amount)} son {impact.debtPercent.toFixed(1).replace('.',',')}% de tu deuda actual.</strong><p>{impact.daysAdvanced!==null&&impact.daysAdvanced>0?`Si ese monto se sumara al aporte mensual, el plan podría acortarse cerca de ${impact.daysAdvanced} días.`:'El efecto en el plazo depende del resto de tus pagos y de las tasas cargadas.'}</p></div>}<div className="split-actions"><button className="button primary" disabled={!amount} onClick={()=>setDecision('saved')}>Prefiero guardarlo</button><button className="button secondary" disabled={!amount} onClick={()=>setDecision('bought')}>Lo compro igual</button></div></>}</Modal>}
  {modal==='support'&&<Modal title="Vamos con lo próximo" onClose={()=>setModal(null)}><div className="support-modal">{f.progress.paid>0?<><p>Cuando arrancaste debías <strong>{formatARS(f.progress.initial)}</strong>.</p><p>Hoy quedan <strong>{formatARS(f.progress.remaining)}</strong>. Ya sacaste de encima <strong>{formatARS(f.progress.paid)}</strong>: un {Math.round(f.progress.percent)}% del camino.</p><p>Todavía falta, pero no estás donde empezaste.</p></>:<p>Recién estás poniendo los números en orden. Eso ya sirve porque ahora podemos ver el problema entero y dividirlo.</p>}<div className="calm-card"><strong>No necesitás resolver {formatARS(f.progress.remaining)} hoy.</strong><p>{next[0]?`Lo próximo son ${formatARS(Math.min(next[0].balance,Math.max(next[0].minimumPayment,next[0].agreedPayment??0)))} para ${next[0].name}. Vamos con eso primero.`:'Por ahora, revisá el próximo paso del plan.'}</p></div><button className="button primary full" onClick={()=>setModal(null)}>Volver</button></div></Modal>}
  {modal==='explain'&&<Modal title="Cómo calculamos lo disponible" onClose={()=>setModal(null)}><div className="calculation"><p>Ingresan <strong>{formatARS(f.budget.income)}</strong>.</p><p>Los gastos esenciales suman <strong>− {formatARS(f.budget.essential)}</strong>.</p><p>Los pagos mínimos o cuotas suman <strong>− {formatARS(f.budget.mandatoryDebt)}</strong>.</p><hr/><p>Quedan <strong>{formatARS(f.budget.availableExtra)}</strong> disponibles para adelantar deuda.</p></div><p className="help">Los gastos modificables se muestran aparte: vos decidís qué hacer con ellos. Nunca recomendamos dejar un mínimo sin cubrir para acelerar otra deuda.</p></Modal>}</Page>}
function Crisis({deficit,debts}:{deficit:number;debts:Debt[]}){return <section className="crisis"><p className="eyebrow">Este mes</p><h2>No cierran los números.</h2><div className="crisis-number"><span>Faltan para cubrir esenciales y pagos cargados</span><strong>{formatARS(deficit)}</strong></div><h3>Pagos próximos</h3>{debts.slice(0,4).map(d=><div className="obligation" key={d.id}><span>{d.name}<small>{formatDate(d.dueDate)}</small></span><strong>{formatARS(Math.min(d.balance,Math.max(d.minimumPayment,d.agreedPayment??0)))}</strong></div>)}<p>Podés revisar gastos variables, actualizar ingresos, consultar si alguna deuda tiene plan de pago o comunicarte con el acreedor para conocer alternativas. Si la situación lo requiere, buscá asesoramiento profesional.</p><strong>No vamos a sugerirte dejar de pagar una obligación para acelerar otra.</strong></section>}
