import { useState } from 'react'
import { AmountInput } from '../components/AmountInput'
import { ExchangeReference } from '../components/ExchangeReference'
import { Modal } from '../components/Modal'
import { Page } from '../components/Page'
import { installmentWarning,monthlyObligation } from '../financial-engine'
import { useExchangeRates } from '../hooks/useExchangeRates'
import { useFinance } from '../hooks/useFinance'
import { db } from '../storage/db'
import type { Debt,DebtType,DueWindow } from '../types/models'
import { debtDueLabel,debtTypeLabels,dueWindowLabels,paymentLabel } from '../types/labels'
import { formatDate,formatMoney,id,todayISO } from '../utils/format'

const reasons=['Me genera ansiedad','Afecta una relación','Puede generar un problema legal','Está vencida','Tiene intereses altos','Quiero sacármela de encima']
const blank=(order:number):Debt=>({id:id(),name:'',type:'credit_card',balance:0,initialBalance:0,minimumPayment:0,personalUrgency:3,priorityReasons:[],manualOrder:order,createdAt:todayISO(),currency:'ARS',status:'active',canPrepay:'unknown'})
const fixed=(type:DebtType)=>['personal_loan','bank_loan','fintech_loan','mortgage'].includes(type)
const dueText=(debt:Debt)=>debt.dueDate?formatDate(debt.dueDate):debtDueLabel(debt)

export function Debts(){
 const {debts,payments,settings}=useFinance(),rates=useExchangeRates(true),[editing,setEditing]=useState<Debt|null>(null),[paymentAnswer,setPaymentAnswer]=useState<'yes'|'no'|'unknown'>('unknown'),[installmentAnswer,setInstallmentAnswer]=useState<'yes'|'no'>('no'),[showRates,setShowRates]=useState(false)
 const ordered=[...debts].filter(debt=>debt.status==='active'&&debt.balance>0).sort((a,b)=>a.manualOrder-b.manualOrder),completed=debts.filter(debt=>debt.status==='paid'||debt.balance===0).sort((a,b)=>(b.paidAt??'').localeCompare(a.paidAt??''))
 const open=(debt:Debt)=>{setEditing({...debt});setPaymentAnswer(monthlyObligation(debt)>0?'yes':'unknown');setInstallmentAnswer(debt.remainingInstallments!==undefined?'yes':'no');setShowRates(false)}
 const changeType=(type:DebtType)=>setEditing(current=>{if(!current)return current;const amount=monthlyObligation(current);return fixed(type)?{...current,type,installmentAmount:amount||undefined,minimumPayment:0,agreedPayment:undefined}:type==='credit_card'?{...current,type,minimumPayment:amount,installmentAmount:undefined,agreedPayment:undefined}:{...current,type,agreedPayment:amount||undefined,installmentAmount:undefined,minimumPayment:0}})
 const setPayment=(value:number)=>setEditing(current=>current?fixed(current.type)?{...current,installmentAmount:value||undefined,minimumPayment:0,agreedPayment:undefined}:current.type==='credit_card'?{...current,minimumPayment:value,installmentAmount:undefined,agreedPayment:undefined}:{...current,agreedPayment:value||undefined,installmentAmount:undefined,minimumPayment:0}:current)
 const clearPayment=(answer:'no'|'unknown')=>{setPaymentAnswer(answer);setEditing(current=>current?{...current,minimumPayment:0,agreedPayment:undefined,installmentAmount:undefined}:current)}
 const save=async()=>{if(!editing||!editing.name.trim()||editing.balance<0)return;let next={...editing,initialBalance:editing.initialBalance||editing.balance,status:editing.balance>0?'active' as const:'paid' as const};if(next.currency==='USD'&&!next.conversionRate){const preferred=next.type==='credit_card'?'card':settings.preferredConversion==='manual'?'manual':undefined,rate=preferred==='manual'?settings.manualExchangeRate:preferred?rates.rates[preferred]?.sell:undefined;if(rate&&preferred)next={...next,conversionRate:rate,conversionSource:preferred,conversionDate:new Date().toISOString(),initialConvertedBalanceARS:next.initialConvertedBalanceARS??next.initialBalance*rate}}await db.debts.put(next);setEditing(null)}
 const remove=async(debt:Debt)=>{if(confirm(`¿Eliminar “${debt.name}”? Los pagos asociados también se eliminarán.`))await db.transaction('rw',db.debts,db.payments,async()=>{await db.debts.delete(debt.id);await db.payments.where('debtId').equals(debt.id).delete()})}
 const move=async(debt:Debt,direction:-1|1)=>{const index=ordered.findIndex(item=>item.id===debt.id),swap=ordered[index+direction];if(!swap)return;await db.transaction('rw',db.debts,async()=>{await db.debts.put({...debt,manualOrder:swap.manualOrder});await db.debts.put({...swap,manualOrder:debt.manualOrder})})}
 return <Page title="Deudas" eyebrow="Qué debés" action={<button className="button primary small" onClick={()=>open(blank(debts.length))}>+ Agregar deuda</button>}>
  <p className="support-line">Con nombre y saldo alcanza para empezar. Sumá cuotas o tasas sólo si las conocés.</p>
  <div className="debt-grid">{ordered.length?ordered.map((debt,index)=><article className="debt-card compact" key={debt.id} role="button" tabIndex={0} onClick={()=>open(debt)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open(debt)}}}><div className="compact-debt-head"><div><small>{debtTypeLabels[debt.type]} · {dueText(debt)}</small><h2>{debt.name}</h2></div><strong>{formatMoney(debt.balance,debt.currency)}</strong></div><div className="compact-debt-meta"><span>{paymentLabel(debt.type)} <strong>{formatMoney(monthlyObligation(debt),debt.currency)}</strong></span><span>Estimación <strong>{debt.annualRate!==undefined&&monthlyObligation(debt)>0?'más completa':'básica'}</strong></span><div className="reorder-buttons"><button disabled={index===0} aria-label={`Subir ${debt.name}`} onClick={event=>{event.stopPropagation();move(debt,-1)}}>↑</button><button disabled={index===ordered.length-1} aria-label={`Bajar ${debt.name}`} onClick={event=>{event.stopPropagation();move(debt,1)}}>↓</button></div></div></article>):<div className="empty large"><h2>No hay deudas activas.</h2><button className="button primary" onClick={()=>open(blank(0))}>Agregar una deuda</button></div>}</div>
  {completed.length>0&&<details className="completed-debts"><summary>Deudas terminadas ({completed.length})</summary><div>{completed.map(debt=><button key={debt.id} onClick={()=>open(debt)}><span>✓</span><strong>{debt.name}</strong><small>Pagada {debt.paidAt?`el ${formatDate(debt.paidAt.slice(0,10))}`:''}</small></button>)}</div></details>}
  {editing&&<Modal title={debts.some(debt=>debt.id===editing.id)?'Editar deuda':'Nueva deuda'} onClose={()=>setEditing(null)}>
   <div className="debt-essential-grid"><label className="field"><span>Nombre *</span><input value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})} placeholder="Ej. Visa Galicia" autoFocus/></label><label className="field"><span>Tipo</span><select value={editing.type} onChange={event=>changeType(event.target.value as DebtType)}>{Object.entries(debtTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Saldo pendiente *</span><AmountInput currency={editing.currency} value={editing.balance||''} onChange={value=>setEditing({...editing,balance:value})}/></label><fieldset className="segmented currency-segment"><legend>Moneda</legend>{(['ARS','USD'] as const).map(currency=><button type="button" aria-pressed={editing.currency===currency} className={editing.currency===currency?'selected':''} key={currency} onClick={()=>setEditing({...editing,currency})}>{currency}</button>)}</fieldset></div>
   <fieldset className="choice-block"><legend>¿Cuándo suele vencer?</legend><div className="segmented due-window">{(['early','mid','late'] as DueWindow[]).map(window=><button type="button" aria-pressed={editing.dueWindow===window&&!editing.dueDate} className={editing.dueWindow===window&&!editing.dueDate?'selected':''} key={window} onClick={()=>setEditing({...editing,dueWindow:window,dueDate:undefined})}>{dueWindowLabels[window].replace(' de mes','')}</button>)}</div></fieldset>
   <fieldset className="choice-block"><legend>¿Tenés {paymentLabel(editing.type).toLocaleLowerCase('es-AR')}?</legend><div className="segmented answer-segment"><button type="button" aria-pressed={paymentAnswer==='yes'} className={paymentAnswer==='yes'?'selected':''} onClick={()=>setPaymentAnswer('yes')}>Sí</button><button type="button" aria-pressed={paymentAnswer==='no'} className={paymentAnswer==='no'?'selected':''} onClick={()=>clearPayment('no')}>No</button><button type="button" aria-pressed={paymentAnswer==='unknown'} className={paymentAnswer==='unknown'?'selected':''} onClick={()=>clearPayment('unknown')}>No sé</button></div>{paymentAnswer==='yes'&&<label className="field compact-field"><span>{paymentLabel(editing.type)}</span><AmountInput currency={editing.currency} value={monthlyObligation(editing)||''} onChange={setPayment}/></label>}</fieldset>
   {paymentAnswer==='yes'&&fixed(editing.type)&&<fieldset className="choice-block"><legend>¿Sabés cuántas cuotas faltan?</legend><div className="segmented answer-segment"><button type="button" aria-pressed={installmentAnswer==='yes'} className={installmentAnswer==='yes'?'selected':''} onClick={()=>setInstallmentAnswer('yes')}>Sí</button><button type="button" aria-pressed={installmentAnswer==='no'} className={installmentAnswer==='no'?'selected':''} onClick={()=>{setInstallmentAnswer('no');setEditing({...editing,remainingInstallments:undefined})}}>No</button></div>{installmentAnswer==='yes'&&<label className="field compact-field"><span>Cuotas restantes</span><input type="number" inputMode="numeric" min="0" step="1" value={editing.remainingInstallments??''} onChange={event=>setEditing({...editing,remainingInstallments:event.target.value?Math.max(0,Math.floor(Number(event.target.value))):undefined})}/></label>}</fieldset>}
   {installmentWarning(editing)&&<div className="warning-box"><strong>Revisá estos datos</strong><p>{installmentWarning(editing)}</p></div>}
   <details className="advanced-debt"><summary>+ Más detalles</summary><div className="form-grid"><label className="field"><span>Fecha exacta <small>(opcional)</small></span><input type="date" value={editing.dueDate??''} onChange={event=>setEditing({...editing,dueDate:event.target.value||undefined})}/></label><label className="field"><span>Entidad / acreedor</span><input value={editing.creditor??''} onChange={event=>setEditing({...editing,creditor:event.target.value})}/></label><label className="field"><span>TNA % <button className="inline-help" type="button" onClick={()=>setShowRates(!showRates)}>¿qué es?</button></span><input type="number" inputMode="decimal" min="0" max="1000" value={editing.annualRate??''} onChange={event=>setEditing({...editing,annualRate:event.target.value?Math.max(0,Number(event.target.value)):undefined})}/></label><label className="field"><span>CFT %</span><input type="number" inputMode="decimal" min="0" max="2000" value={editing.cft??''} onChange={event=>setEditing({...editing,cft:event.target.value?Math.max(0,Number(event.target.value)):undefined})}/></label></div><fieldset className="choice-block"><legend>¿Podés adelantar pagos?</legend><div className="segmented answer-segment">{([['yes','Sí'],['no','No'],['unknown','No sé']] as const).map(([value,label])=><button type="button" aria-pressed={(editing.canPrepay??'unknown')===value} className={(editing.canPrepay??'unknown')===value?'selected':''} key={value} onClick={()=>setEditing({...editing,canPrepay:value})}>{label}</button>)}</div></fieldset>{showRates&&<div className="help-box"><strong>Tasas, en simple</strong><p>La TNA ayuda a estimar intereses. El CFT sirve para comparar costos, pero no lo usamos como si fuera una tasa mensual.</p></div>}<fieldset className="urgency"><legend>Prioridad personal: {editing.personalUrgency}/5</legend><input aria-label="Prioridad personal" type="range" min="1" max="5" value={editing.personalUrgency} onChange={event=>setEditing({...editing,personalUrgency:Number(event.target.value) as Debt['personalUrgency']})}/></fieldset><fieldset className="reason-list"><legend>Motivos <small>(opcional)</small></legend>{reasons.map(reason=><label key={reason}><input type="checkbox" checked={editing.priorityReasons.includes(reason)} onChange={event=>setEditing({...editing,priorityReasons:event.target.checked?[...editing.priorityReasons,reason]:editing.priorityReasons.filter(item=>item!==reason)})}/>{reason}</label>)}</fieldset><label className="field"><span>Comentarios</span><textarea value={editing.notes??''} onChange={event=>setEditing({...editing,notes:event.target.value})}/></label></details>
   {editing.currency==='USD'&&<><div className="help-box"><strong>El resumen manda.</strong><p>La cotización sólo se usa como referencia informativa y queda bloqueada para el progreso.</p></div><ExchangeReference usd={editing.balance} rates={rates.rates} error={rates.error} onRetry={()=>rates.refresh()}/></>}
   {editing.annualRate===undefined?<p className="estimation-precision"><strong>Estimación básica.</strong> Esta estimación no incluye intereses porque no cargaste una tasa.</p>:monthlyObligation(editing)>0&&<p className="estimation-precision"><strong>Estimación más completa.</strong> Tenemos saldo, pago mensual y tasa.</p>}
   {debts.some(debt=>debt.id===editing.id)&&<section className="debt-payment-history"><h3>Pagos registrados</h3>{payments.filter(payment=>payment.debtId===editing.id).length?payments.filter(payment=>payment.debtId===editing.id).sort((a,b)=>b.date.localeCompare(a.date)).map(payment=><div className="money-row" key={payment.id}><span>{formatDate(payment.date)}</span><strong>{formatMoney(payment.amount,payment.currency)}</strong></div>):<p className="help">Todavía no hay pagos registrados.</p>}</section>}
   <div className="modal-actions">{debts.some(debt=>debt.id===editing.id)&&<button className="button danger-link" onClick={()=>{remove(editing);setEditing(null)}}>Eliminar</button>}<button className="button ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="button primary" disabled={!editing.name.trim()} onClick={save}>Guardar deuda</button></div>
  </Modal>}
 </Page>
}
