import { useRef,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { Modal } from '../components/Modal'
import { Page } from '../components/Page'
import { useFinance } from '../hooks/useFinance'
import { changeExperienceMode } from '../services/experience-mode'
import { clearAllData,exportData,importData,parseBackup } from '../storage/backup'
import { db } from '../storage/db'
import { characterLabels } from '../types/labels'
import type { ProgressCharacter } from '../types/models'

export function More(){
  const finance=useFinance(),navigate=useNavigate(),fileRef=useRef<HTMLInputElement>(null)
  const [modal,setModal]=useState<'delete'|'import'|null>(null),[confirmation,setConfirmation]=useState(''),[pending,setPending]=useState<ReturnType<typeof parseBackup>|null>(null),[status,setStatus]=useState('')
  const update=(changes:Partial<typeof finance.settings>)=>db.settings.put({id:'main',...finance.settings,...changes})
  const setMode=async(mode:'simple'|'full')=>{await db.settings.put({id:'main',...changeExperienceMode(finance.settings,mode)});navigate(mode==='simple'?'/simple':'/plan')}
  const download=async()=>{const data=await exportData(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`deudarg-backup-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);setStatus('Backup exportado.')}
  const readFile=async(file?:File)=>{if(!file)return;try{setPending(parseBackup(await file.text()));setModal('import')}catch{setStatus('Ese archivo no es un backup válido. Tus datos siguen intactos.')}}
  const doImport=async()=>{if(!pending)return;await importData(pending);setModal(null);setPending(null);setStatus('Datos recuperados correctamente.')}
  const doDelete=async()=>{if(confirmation!=='BORRAR')return;await clearAllData();setModal(null);navigate('/')}
  return <Page title="Más" eyebrow="Configuración">
    <p className="support-line">Preferencias, herramientas y control de tus datos.</p>
    {status&&<div className="toast" role="status">{status}</div>}
    <section className="section-card about-entry"><div><p className="eyebrow">DeudARG</p><h2>Sobre el proyecto</h2><p>Quién lo hizo, por qué existe y cómo enviar feedback.</p></div><Link className="button secondary" to="/sobre-el-proyecto">Conocer el proyecto</Link></section>
    <div className="settings-grid">
      <section className="section-card"><h2>Experiencia</h2><div className="mode-switch"><button className={finance.settings.experienceMode==='simple'?'selected':''} onClick={()=>setMode('simple')}><strong>Simple</strong><small>Saldo, progreso y pagos.</small></button><button className={finance.settings.experienceMode!=='simple'?'selected':''} onClick={()=>setMode('full')}><strong>Completa</strong><small>Plan, gastos y estrategias.</small></button></div><Toggle label="Mostrar ayudas flotantes" checked={finance.settings.showQuickHelp} onChange={value=>update({showQuickHelp:value})}/><Toggle label="Mostrar reflexiones opcionales" checked={finance.settings.showReflections} onChange={value=>update({showReflections:value})}/><Toggle label="Reducir animaciones" checked={finance.settings.reduceMotion} onChange={value=>update({reduceMotion:value})}/></section>
      <section className="section-card"><h2>Indicador de progreso</h2><div className="character-grid compact">{Object.entries(characterLabels).map(([key,item])=><button className={finance.settings.progressCharacter===key?'selected':''} key={key} onClick={()=>update({progressCharacter:key as ProgressCharacter})}><span>{item.icon}</span><small>{item.label}</small></button>)}</div></section>
      <section className="section-card"><h2>Herramientas</h2><Link className="settings-link" to="/herramientas"><span>↔</span><div><strong>Conversor y simulador</strong><small>Probá cambios sin modificar tu plan.</small></div><b>›</b></Link><Link className="settings-link" to="/entender"><span>i</span><div><strong>Entender conceptos</strong><small>TNA, CFT, mínimos y estrategias.</small></div><b>›</b></Link></section>
      <section className="section-card"><h2>Conversión USD</h2><label className="field"><span>Referencia preferida</span><select value={finance.settings.preferredConversion} onChange={event=>update({preferredConversion:event.target.value as typeof finance.settings.preferredConversion})}><option value="card">Dólar tarjeta</option><option value="blue">Dólar blue</option><option value="manual">Cotización manual</option></select></label>{finance.settings.preferredConversion==='manual'&&<><label className="field"><span>Pesos por USD</span><input type="number" min="0" value={finance.settings.manualExchangeRate??''} onChange={event=>update({manualExchangeRate:Number(event.target.value)||undefined})}/></label><label className="field"><span>Motivo o fuente <small>(opcional)</small></span><input value={finance.settings.manualExchangeReason??''} onChange={event=>update({manualExchangeReason:event.target.value})}/></label></>}</section>
      <section className="section-card"><h2>Tus datos</h2><button className="settings-link" onClick={download}><span>↓</span><div><strong>Exportar mis datos</strong><small>Descargar un archivo JSON local.</small></div><b>›</b></button><button className="settings-link" onClick={()=>fileRef.current?.click()}><span>↑</span><div><strong>Importar backup</strong><small>Se valida antes de reemplazar nada.</small></div><b>›</b></button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={event=>readFile(event.target.files?.[0])}/><button className="settings-link danger" onClick={()=>{setConfirmation('');setModal('delete')}}><span>×</span><div><strong>Borrar todos mis datos</strong><small>Elimina la información financiera local.</small></div><b>›</b></button></section>
      <section className="section-card"><h2>Información</h2><Link className="settings-link" to="/privacidad"><span>🔒</span><div><strong>Privacidad</strong><small>Qué se guarda y dónde.</small></div><b>›</b></Link><Link className="settings-link" to="/como-funciona"><span>?</span><div><strong>Cómo funciona</strong><small>Cálculos, límites y responsabilidad.</small></div><b>›</b></Link></section>
    </div>
    <div className="disclaimer">Esta herramienta brinda cálculos, simulaciones e información educativa. No constituye asesoramiento financiero, jurídico, contable ni crediticio.</div>
    {modal==='import'&&<Modal title="Importar este backup" onClose={()=>setModal(null)}><p>El archivo contiene <strong>{pending?.debts.length} deudas</strong>, <strong>{pending?.expenses.length} gastos</strong> y <strong>{pending?.payments.length} pagos</strong>.</p><div className="warning-box"><strong>Esto reemplazará los datos actuales.</strong><p>Si querés conservarlos, exportalos antes.</p></div><div className="modal-actions"><button className="button ghost" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" onClick={doImport}>Reemplazar e importar</button></div></Modal>}
    {modal==='delete'&&<Modal title="Borrar todos mis datos" onClose={()=>setModal(null)}><p>Se eliminarán ingresos, gastos, deudas, pagos, objetivos e historial de este dispositivo.</p><div className="danger-box"><strong>No se puede deshacer salvo que tengas un backup.</strong></div><label className="field"><span>Escribí <strong>BORRAR</strong> para confirmar</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><div className="modal-actions"><button className="button ghost" onClick={()=>setModal(null)}>Cancelar</button><button className="button danger-button" disabled={confirmation!=='BORRAR'} onClick={doDelete}>Borrar definitivamente</button></div></Modal>}
  </Page>
}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
