import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { useNavigate } from 'react-router-dom'
import { AmountInput } from '../components/AmountInput'
import { db } from '../storage/db'
import type { Debt, DebtType, ExpenseKind, Income } from '../types/models'
import { debtTypeLabels } from '../types/labels'
import { id, todayISO } from '../utils/format'

const steps=['Ingresos','Gastos esenciales','Gastos modificables','Deudas','Prioridades','Resultado']
const essential=['Alquiler / vivienda','Expensas','Comida','Servicios','Transporte','Salud','Educación','Personas a cargo','Medicamentos','Otros esenciales']
const adjustable=['Delivery','Cigarrillos','Alcohol','Suscripciones','Salidas','Compras','Entretenimiento','Snacks / golosinas','Otros modificables']
export function Onboarding(){const navigate=useNavigate(),[step,setStep]=useState(0);const incomes=useLiveQuery(()=>db.incomes.toArray(),[])??[],expenses=useLiveQuery(()=>db.expenses.toArray(),[])??[],debts=useLiveQuery(()=>db.debts.toArray(),[])??[]
  const setIncome=async(kind:Income['kind'],label:string,amount:number)=>{const existing=incomes.find(i=>i.kind===kind);await db.incomes.put({id:existing?.id??id(),kind,label,amount})}
  const setExpense=async(label:string,kind:ExpenseKind,amount:number)=>{const existing=expenses.find(e=>e.label===label&&e.kind===kind);if(existing)await db.expenses.put({...existing,amount});else await db.expenses.put({id:id(),label,kind,amount})}
  const addDebt=async()=>{const order=debts.length;const debt:Debt={id:id(),name:`Deuda ${order+1}`,type:'credit_card',balance:0,initialBalance:0,minimumPayment:0,personalUrgency:3,priorityReasons:[],manualOrder:order,createdAt:todayISO(),currency:'ARS',status:'active'};await db.debts.add(debt)}
  const updateDebt=async(debt:Debt,changes:Partial<Debt>)=>{const next={...debt,...changes};if(changes.balance!==undefined&&debt.initialBalance===0)next.initialBalance=changes.balance;await db.debts.put(next)}
  const finish=async()=>{const settings=await db.settings.get('main');if(settings)await db.settings.put({...settings,onboardingComplete:true,experienceMode:'full',lastMonthlyReview:todayISO()});navigate('/simular')}
  return <div className="onboarding"><header><button className="brand plain" onClick={()=>navigate('/')}>↗ Proyecto Salida</button><span>Se guarda automáticamente</span></header><div className="stepper" aria-label={`Paso ${step+1} de ${steps.length}`}><div style={{width:`${(step+1)/steps.length*100}%`}}/><span>{step+1} de {steps.length}</span></div><main><p className="eyebrow">{steps[step]}</p>{step===0&&<section><h1>¿Cuánto entra por mes?</h1><p>No hace falta que sea exacto. Podés actualizarlo cuando cambie.</p><Field label="Sueldo neto"><AmountInput value={incomes.find(i=>i.kind==='salary')?.amount??''} onChange={v=>setIncome('salary','Sueldo neto',v)}/></Field><Field label="Ingresos variables"><AmountInput value={incomes.find(i=>i.kind==='variable')?.amount??''} onChange={v=>setIncome('variable','Ingresos variables',v)}/></Field><Field label="Otros ingresos"><AmountInput value={incomes.find(i=>i.kind==='other')?.amount??''} onChange={v=>setIncome('other','Otros ingresos',v)}/></Field></section>}
  {step===1&&<ExpenseStep title="Lo que necesitás para vivir" text="Vos decidís qué es esencial. Después podés mover cualquier gasto." labels={essential} kind="essential" expenses={expenses} setExpense={setExpense}/>} {step===2&&<ExpenseStep title="Acá quizá haya margen" text="No significa que esté mal gastarlo. Solo separamos lo que podrías revisar si te sirve." labels={adjustable} kind="adjustable" expenses={expenses} setExpense={setExpense}/>} 
  {step===3&&<section><h1>Carguemos tus deudas</h1><p>No necesitás saber la tasa. Con saldo y pago mínimo ya podemos ordenar bastante.</p>{debts.map(d=><div className="inline-card debt-onboard" key={d.id}><input aria-label="Nombre de la deuda" value={d.name} onChange={e=>updateDebt(d,{name:e.target.value})}/><select aria-label="Tipo" value={d.type} onChange={e=>updateDebt(d,{type:e.target.value as DebtType})}>{Object.entries(debtTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Moneda" value={d.currency} onChange={e=>updateDebt(d,{currency:e.target.value as Debt['currency']})}><option value="ARS">Pesos argentinos</option><option value="USD">Dólares</option></select><label>Saldo pendiente<AmountInput currency={d.currency} value={d.balance||''} onChange={v=>updateDebt(d,{balance:v})}/></label><label>Pago mínimo o cuota<AmountInput currency={d.currency} value={d.minimumPayment||''} onChange={v=>updateDebt(d,{minimumPayment:v})}/></label></div>)}<button className="button secondary full" onClick={addDebt}>+ Agregar deuda</button>{!debts.length&&<button className="button primary full" onClick={addDebt}>Agregar mi primera deuda</button>}</section>}
  {step===4&&<section><h1>No todo pasa por los intereses</h1><p>Quizá te pese más deberle a una persona que al banco. Está bien: podemos tenerlo en cuenta.</p>{debts.length?debts.map(d=><div className="priority-row" key={d.id}><span><strong>{d.name}</strong><small>Urgencia personal</small></span><div className="rating">{[1,2,3,4,5].map(n=><button aria-label={`Urgencia ${n}`} className={d.personalUrgency===n?'active':''} key={n} onClick={()=>updateDebt(d,{personalUrgency:n as Debt['personalUrgency']})}>{n}</button>)}</div></div>):<div className="empty">Todavía no cargaste deudas. Podés volver al paso anterior.</div>}</section>}
  {step===5&&<section><h1>Ya podemos ver el panorama</h1><p>Cargaste {debts.length} {debts.length===1?'deuda':'deudas'}, {expenses.filter(e=>e.amount>0).length} gastos y {incomes.filter(i=>i.amount>0).length} fuentes de ingreso.</p><div className="calm-card"><strong>No hace falta resolver todo hoy.</strong><p>Ahora vamos a comparar caminos posibles sin decirte que uno es “el correcto”.</p></div></section>}
  </main><footer><button className="button ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}>Atrás</button>{step<steps.length-1?<button className="button primary" onClick={()=>setStep(s=>s+1)}>Continuar</button>:<button className="button primary" onClick={finish}>Comparar estrategias</button>}</footer></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function ExpenseStep({title,text,labels,kind,expenses,setExpense}:{title:string;text:string;labels:string[];kind:ExpenseKind;expenses:{label:string;amount:number;kind:ExpenseKind}[];setExpense:(l:string,k:ExpenseKind,a:number)=>void}){return <section><h1>{title}</h1><p>{text}</p><div className="expense-grid">{labels.map(label=><Field key={label} label={label}><AmountInput value={expenses.find(e=>e.label===label&&e.kind===kind)?.amount??''} onChange={v=>setExpense(label,kind,v)}/></Field>)}</div></section>}
