import { useState } from 'react'
import { Page } from '../components/Page'
import { ProgressTrack } from '../components/ProgressTrack'
import { useFinance } from '../hooks/useFinance'
import { db } from '../storage/db'
import { characterLabels } from '../types/labels'
import type { ProgressCharacter } from '../types/models'
import { formatARS, formatDate, id, todayISO } from '../utils/format'
export function Progress(){const f=useFinance(),[saved,setSaved]=useState(false);const snapshot=async()=>{await db.snapshots.add({id:id(),date:todayISO(),incomeTotal:f.budget.income,essentialTotal:f.budget.essential,adjustableTotal:f.budget.adjustable,debtTotal:f.progress.remaining});setSaved(true)};const changeCharacter=async(c:ProgressCharacter)=>{const s=await db.settings.get('main');if(s)await db.settings.put({...s,progressCharacter:c})};const max=Math.max(...f.snapshots.map(s=>s.debtTotal),f.progress.initial,1)
  return <Page title="Tu progreso" eyebrow="Lo que cambió" action={<button className="button secondary small" onClick={snapshot}>Cerrar este mes</button>}><p className="support-line">Un mes complicado no borra los anteriores. Si cambió tu situación, recalculamos.</p>{saved&&<div className="toast" role="status">Guardamos una foto de este mes en el dispositivo.</div>}<ProgressTrack percent={f.progress.percent} character={f.settings.progressCharacter} paid={f.progress.paid} remaining={f.progress.remaining}/><div className="summary-strip"><span><small>Deuda inicial</small><strong>{formatARS(f.progress.initial)}</strong></span><span><small>Reducción total</small><strong>{formatARS(f.progress.paid)}</strong></span><span><small>Pagos registrados</small><strong>{f.payments.length}</strong></span><span><small>Meses guardados</small><strong>{f.snapshots.length}</strong></span></div><section className="section-card"><div className="section-title"><div><p className="eyebrow">Historial local</p><h2>Evolución de deuda</h2></div></div>{f.snapshots.length?<div className="chart" role="img" aria-label="Gráfico de evolución de la deuda">{f.snapshots.slice(-12).map(s=><div className="bar-wrap" key={s.id}><span className="bar-value">{Math.round(s.debtTotal/1000)}k</span><div className="bar" style={{height:`${Math.max(5,s.debtTotal/max*100)}%`}}/><small>{formatDate(s.date).slice(3)}</small></div>)}</div>:<div className="empty">Cuando cierres tu primer mes, vas a poder ver tu evolución acá.</div>}</section><section className="section-card"><div className="section-title"><div><p className="eyebrow">Personalizar progreso</p><h2>Elegí quién avanza</h2></div></div><div className="character-grid">{Object.entries(characterLabels).map(([key,c])=><button className={f.settings.progressCharacter===key?'selected':''} key={key} onClick={()=>changeCharacter(key as ProgressCharacter)}><span>{c.icon}</span><small>{c.label}</small></button>)}</div></section><section className="section-card"><h2>Pagos realizados</h2>{f.payments.length?[...f.payments].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(p=><div className="money-row" key={p.id}><span>{f.debts.find(d=>d.id===p.debtId)?.name??'Deuda eliminada'}<small>{formatDate(p.date)}</small></span><strong>{formatARS(p.amount)}</strong></div>):<div className="empty">Cuando registres un pago, va a aparecer acá.</div>}</section></Page>}
