import { useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { AmountInput } from '../components/AmountInput'
import { ExchangeReference } from '../components/ExchangeReference'
import { useExchangeRates } from '../hooks/useExchangeRates'
import { db,defaultSettings } from '../storage/db'
import type { Currency } from '../types/models'
import { id,todayISO } from '../utils/format'

export function SimpleStart(){const navigate=useNavigate(),rates=useExchangeRates(true),[name,setName]=useState(''),[amount,setAmount]=useState(0),[currency,setCurrency]=useState<Currency>('ARS'),[saving,setSaving]=useState(false);const save=async()=>{if(amount<=0)return;setSaving(true);const current=await db.settings.get('main')??defaultSettings,created=id();await db.transaction('rw',db.debts,db.settings,async()=>{await db.debts.add({id:created,name:name.trim()||'Mi deuda',type:'other',balance:amount,initialBalance:amount,minimumPayment:0,personalUrgency:3,priorityReasons:[],manualOrder:await db.debts.count(),createdAt:todayISO(),currency,status:'active'});await db.settings.put({id:'main',...current,experienceMode:'simple',onboardingComplete:true})});navigate('/simple')};return <div className="simple-flow"><header><Link to="/" className="brand"><span className="brand-mark">↗</span>Proyecto Salida</Link><span>Modo Simple</span></header><main><p className="eyebrow">Empezá en menos de un minuto</p><h1>¿Cuánto debés hoy?</h1><p>Con esto alcanza para empezar. Después podés sumar otras deudas o pasar al plan completo sin perder nada.</p><label className="field"><span>Nombre <small>(opcional)</small></span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Por ejemplo, tarjeta" autoFocus/></label><fieldset className="currency-choice"><legend>Moneda</legend><button type="button" className={currency==='ARS'?'selected':''} onClick={()=>setCurrency('ARS')}>Pesos (ARS)</button><button type="button" className={currency==='USD'?'selected':''} onClick={()=>setCurrency('USD')}>Dólares (USD)</button></fieldset><label className="field"><span>Saldo actual</span><AmountInput currency={currency} value={amount||''} onChange={setAmount}/></label>{currency==='USD'&&<ExchangeReference usd={amount} rates={rates.rates} error={rates.error} onRetry={()=>rates.refresh()}/>}<button className="button primary large full" disabled={!amount||saving} onClick={save}>{saving?'Guardando…':'Crear mi seguimiento'}</button><p className="data-note">🔒 Se guarda solamente en este dispositivo. Consultamos cotizaciones públicas sin enviar tus datos financieros.</p></main></div>}
