import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Page } from '../components/Page'
import { orderDebts, projectDebts } from '../financial-engine'
import { useFinance } from '../hooks/useFinance'
import { db } from '../storage/db'
import type { StrategyKind } from '../types/models'
import { strategyLabels } from '../types/labels'
import { formatARS, formatDate } from '../utils/format'
const copy:Record<StrategyKind,string>={avalanche:'Prioriza la deuda con mayor tasa cargada. Generalmente reduce el costo total de intereses.',snowball:'Prioriza el saldo más chico. Permite cerrar deudas antes y ver progreso rápido.',personal:'Usa la urgencia 1–5 que elegiste, aunque el interés no sea el más alto.',manual:'Respeta el orden que definiste. Vos decidís qué va primero.'}
export function Simulate(){const f=useFinance(),[expanded,setExpanded]=useState<StrategyKind|null>(null);const results=useMemo(()=>Object.fromEntries((['avalanche','snowball','personal','manual'] as StrategyKind[]).map(s=>[s,projectDebts(f.debts,f.budget.availableExtra,s)])) as Record<StrategyKind,ReturnType<typeof projectDebts>>,[f.debts,f.budget.availableExtra]);const choose=async(strategy:StrategyKind)=>{const settings=await db.settings.get('main');if(settings)await db.settings.put({...settings,strategy,onboardingComplete:true})};const active=f.debts.filter(d=>d.balance>0)
  if(!active.length)return <Page title="Comparar estrategias" eyebrow="Simulador"><div className="empty large"><span>🧭</span><h2>Necesitamos al menos una deuda pendiente.</h2><Link className="button primary" to="/deudas">Agregar deuda</Link></div></Page>
  return <Page title="Comparar estrategias" eyebrow="Simulador"><p className="support-line">No hay una única estrategia correcta. Mirá el costo, el tiempo y también cuál podrías sostener.</p>{f.budget.deficit>0&&<div className="warning-box"><strong>Primero hay que resolver el déficit mensual de {formatARS(f.budget.deficit)}.</strong><p>No proyectamos pagos extra mientras los esenciales y mínimos cargados no estén cubiertos.</p></div>}<div className="strategy-grid">{(Object.keys(results) as StrategyKind[]).map(kind=>{const r=results[kind],first=f.debts.find(d=>d.id===r.firstCompletedDebtId);return <article className={`strategy-card ${f.settings.strategy===kind?'selected':''}`} key={kind}><div className="strategy-head"><span>{kind==='avalanche'?'↓%':kind==='snowball'?'◌':kind==='personal'?'♥':'☰'}</span><div><h2>{strategyLabels[kind]}</h2>{f.settings.strategy===kind&&<small>Tu plan actual</small>}</div></div><p>{copy[kind]}</p><dl><div><dt>Tiempo estimado</dt><dd>{r.months!==null?`${r.months} meses`:'No calculable'}</dd></div><div><dt>Finalización</dt><dd>{formatDate(r.completionDate??undefined)}</dd></div><div><dt>Intereses estimados</dt><dd>{r.estimatedInterest===null?'Faltan tasas':formatARS(r.estimatedInterest)}</dd></div><div><dt>Primera en terminar</dt><dd>{first?.name??'—'}</dd></div></dl>{r.approximate&&<p className="data-note">Estimación parcial: no inventamos tasas que no cargaste.</p>}<div className="strategy-actions"><button className="button ghost small" onClick={()=>setExpanded(expanded===kind?null:kind)}>{expanded===kind?'Ocultar':'Ver orden'}</button><button className="button primary small" onClick={()=>choose(kind)}>{f.settings.strategy===kind?'Elegida':'Elegir'}</button></div>{expanded===kind&&<ol className="order-list">{orderDebts(f.debts,kind).map((d,i)=><li key={d.id}><span>{i+1}</span>{d.name}<strong>{formatARS(d.balance)}</strong></li>)}</ol>}</article>})}</div><section className="section-card transparency"><h2>¿Cómo sale el dinero extra?</h2><div className="equation"><span><small>Ingresos</small>{formatARS(f.budget.income)}</span><b>−</b><span><small>Esenciales</small>{formatARS(f.budget.essential)}</span><b>−</b><span><small>Mínimos y cuotas</small>{formatARS(f.budget.mandatoryDebt)}</span><b>=</b><span className="result"><small>Para adelantar</small>{formatARS(f.budget.availableExtra)}</span></div><p>Ese es el único monto que distribuimos estratégicamente. No aceleramos una deuda dejando otra obligación mínima sin cubrir.</p></section></Page>}
