import { useState } from 'react'
import { AmountInput } from '../components/AmountInput'
import { Page } from '../components/Page'
import { reductionImpact } from '../financial-engine'
import { useFinance } from '../hooks/useFinance'
import { db } from '../storage/db'
import { formatARS, id, todayISO } from '../utils/format'
const everyday=['Coca-Colas','Paquetes de cigarrillos','Cafés','Hamburguesas','Viajes en colectivo','Litros de nafta','Horas de trabajo','Días de sueldo','Otra cosa']
export function Tools(){const f=useFinance(),[debtAmount,setDebtAmount]=useState(f.progressByCurrency.ARS?.currentOutstanding??0),[unit,setUnit]=useState('Cafés'),[unitPrice,setUnitPrice]=useState(0),[times,setTimes]=useState(0),[label,setLabel]=useState('Delivery'),[current,setCurrent]=useState(0),[target,setTarget]=useState(0),[saved,setSaved]=useState(false);const saving=Math.max(0,current-target),impact=reductionImpact(saving,f.debts,f.budget.availableExtra,f.settings.strategy,f.budget.deficit===0);const saveGoal=async()=>{await db.savingsGoals.add({id:id(),expenseLabel:label,currentAmount:current,targetAmount:target,createdAt:todayISO()});setSaved(true)}
  return <Page title="Probar cambios" eyebrow="Herramientas"><p className="support-line">No son órdenes. Son maneras de entender el impacto antes de decidir.</p><section className="section-card tool-section"><div className="section-title"><div><p className="eyebrow">Conversor</p><h2>¿Cuánto es realmente esta plata?</h2></div><span className="section-emoji">☕</span></div><div className="form-grid"><label className="field"><span>Monto a convertir</span><AmountInput value={debtAmount||''} onChange={setDebtAmount}/></label><label className="field"><span>Convertir a</span><select value={unit} onChange={e=>setUnit(e.target.value)}>{everyday.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Precio actual de una unidad</span><AmountInput value={unitPrice||''} onChange={setUnitPrice}/></label><label className="field"><span>Si reduzco cuántas por mes</span><input type="number" min="0" inputMode="numeric" value={times||''} onChange={e=>setTimes(Math.max(0,Number(e.target.value)||0))}/></label></div>{unitPrice>0&&<div className="big-result"><span>{formatARS(debtAmount)} son aproximadamente</span><strong>{Math.floor(debtAmount/unitPrice).toLocaleString('es-AR')} {unit.toLowerCase()}</strong>{times>0&&<p>Reducir {times} por mes representa {formatARS(times*unitPrice)} mensuales.</p>}</div>}<p className="help">Usamos el precio que vos ingresás. No consultamos precios online.</p></section><section className="section-card tool-section"><div className="section-title"><div><p className="eyebrow">Simulador de recortes</p><h2>¿Qué pasa si cambio esto?</h2></div><span className="section-emoji">✂️</span></div><div className="form-grid"><label className="field wide"><span>Gasto</span><input value={label} onChange={e=>setLabel(e.target.value)}/></label><label className="field"><span>Gasto actual mensual</span><AmountInput value={current||''} onChange={setCurrent}/></label><label className="field"><span>Nuevo objetivo</span><AmountInput value={target||''} onChange={setTarget}/></label></div>{saving>0&&<div className="big-result"><span>Si esto te resulta posible, ahorrarías</span><strong>{formatARS(saving)} por mes</strong><p>{impact.daysAdvanced!==null?`Tu plan podría terminar aproximadamente ${impact.daysAdvanced} días antes.`:'Todavía faltan datos para calcular el cambio en el plazo.'}</p></div>}<button className="button primary" disabled={!saving||!label.trim()} onClick={saveGoal}>Guardar objetivo</button>{saved&&<p className="success-text">Objetivo guardado en este dispositivo.</p>}</section>{f.goals.length>0&&<section className="section-card"><h2>Objetivos guardados</h2>{f.goals.map(g=><div className="money-row" key={g.id}><span>{g.expenseLabel}<small>{formatARS(g.currentAmount)} → {formatARS(g.targetAmount)}</small></span><strong>{formatARS(g.currentAmount-g.targetAmount)}/mes</strong><button onClick={()=>db.savingsGoals.delete(g.id)}>×</button></div>)}</section>}</Page>}
