export interface Article { slug:string;title:string;summary:string;body:{heading?:string;paragraph:string}[];source?:{label:string;url:string} }
export const articles:Article[]=[
{slug:'que-es-tna',title:'Qué es la TNA',summary:'Una tasa anual de referencia, explicada sin fórmulas innecesarias.',body:[{paragraph:'La Tasa Nominal Anual indica un porcentaje anual, pero no muestra por sí sola cómo se acumulan los intereses durante el año ni todos los cargos.'},{heading:'Para qué sirve',paragraph:'Ayuda a tener una referencia, pero no alcanza para comparar el costo completo de dos opciones. Mirá también la TEA, el CFT y las condiciones concretas.'}]},
{slug:'que-es-tea',title:'Qué es la TEA',summary:'La tasa que contempla cómo se acumulan intereses.',body:[{paragraph:'La Tasa Efectiva Anual incorpora el efecto de capitalizar intereses durante el año. Por eso suele ser mayor que la TNA.'},{heading:'En simple',paragraph:'Sirve para entender mejor cuánto crece una deuda en un año si los intereses se van sumando al capital.'}]},
{slug:'que-es-cft',title:'Qué es el CFT',summary:'El número que intenta reunir el costo financiero total.',body:[{paragraph:'El Costo Financiero Total busca incluir la tasa y otros cargos, como comisiones, seguros e impuestos. Para comparar deudas suele ser más representativo que mirar solamente la TNA.'},{heading:'Antes de decidir',paragraph:'Verificá qué incluye exactamente el CFT informado por la entidad y si está expresado con o sin impuestos.'}]},
{slug:'pago-minimo-tarjeta',title:'Qué significa pagar el mínimo',summary:'Qué cubre y por qué la deuda puede seguir creciendo.',body:[{paragraph:'El pago mínimo permite cumplir con el importe exigido para ese resumen, pero el saldo que queda continúa financiado y genera intereses según las condiciones de la tarjeta.'},{heading:'En tu plan',paragraph:'Esta herramienta reserva primero el mínimo que cargaste. Solo después calcula cuánto podrías adelantar.'}]},
{slug:'como-funciona-una-tarjeta',title:'Cómo funciona una tarjeta',summary:'Resumen, vencimiento, saldo financiado y límites.',body:[{paragraph:'Las compras de un período se agrupan en un resumen. Podés pagar el total, financiar parte o, si la entidad lo permite, abonar un mínimo. Lo que no pagás se financia con el costo indicado en el resumen.'}]},
{slug:'mora-y-refinanciacion',title:'Mora y refinanciación',summary:'Dos conceptos distintos que conviene separar.',body:[{paragraph:'La mora aparece cuando una obligación vence sin el pago previsto. Refinanciar significa acordar nuevas condiciones para pagar una deuda. Puede cambiar plazo, cuota y costo total.'},{heading:'Importante',paragraph:'Antes de aceptar una alternativa, pedí el detalle de tasas, cargos, cantidad de cuotas y total a pagar.'}]},
{slug:'avalancha-vs-bola-de-nieve',title:'Avalancha vs. bola de nieve',summary:'Una prioriza costo; la otra, cierres rápidos.',body:[{paragraph:'Avalancha dirige el extra a la deuda con mayor tasa. Suele reducir intereses cuando todas las tasas están disponibles.'},{paragraph:'Bola de nieve dirige el extra al saldo más chico. Puede dar una sensación de avance más temprana. Ninguna es moralmente superior: importa cuál entendés y podés sostener.'}]},
{slug:'situacion-crediticia',title:'Situación crediticia sin miedo',summary:'Qué mirar y dónde consultar información oficial.',body:[{paragraph:'Una situación crediticia negativa es un problema concreto, pero no significa que tu vida financiera haya terminado. La información, los plazos y las categorías pueden cambiar: consultá siempre la fuente oficial.'},{heading:'Privacidad',paragraph:'Proyecto Salida no pide CUIT o CUIL, no consulta la Central de Deudores y no importa información desde allí.'}],source:{label:'Conocer qué es la Central de Deudores — BCRA',url:'https://www.bcra.gob.ar/conocer-que-es-la-central-de-deudores/'}}
]
