import { render,screen } from '@testing-library/react'
import { describe,expect,it } from 'vitest'
import type { CurrencyProgress } from '../financial-engine'
import { CurrencyProgressGroup } from './CurrencyProgressGroup'
const progress=(currency:'ARS'|'USD',percent=20):CurrencyProgress=>({currency,initialTotal:100,currentOutstanding:100-percent,amountPaid:percent,progressRatio:percent/100,progressPercent:percent,activeDebtCount:1})
describe('barras por moneda',()=>{
 it('solo ARS conserva una única barra de progreso total',()=>{render(<CurrencyProgressGroup progress={{ARS:progress('ARS')}} character="car"/>);expect(screen.getAllByRole('progressbar')).toHaveLength(1);expect(screen.getByRole('progressbar',{name:'Progreso total'})).toBeInTheDocument();expect(screen.queryByText(/Progreso en dólares/i)).not.toBeInTheDocument()})
 it('solo USD no reserva una barra ARS vacía',()=>{render(<CurrencyProgressGroup progress={{USD:progress('USD')}} character="car"/>);expect(screen.getAllByRole('progressbar')).toHaveLength(1);expect(screen.getByRole('progressbar',{name:'Progreso en dólares'})).toBeInTheDocument();expect(screen.queryByText(/Progreso en pesos/i)).not.toBeInTheDocument();expect(document.querySelector('.compact-progress')).not.toBeInTheDocument()})
 it('apila ARS y USD como porcentajes, montos y marcadores independientes',()=>{render(<CurrencyProgressGroup progress={{ARS:progress('ARS',25),USD:progress('USD',50)}} character="car"/>);expect(screen.getByRole('progressbar',{name:'Progreso en pesos'})).toHaveAttribute('aria-valuenow','25');expect(screen.getByRole('progressbar',{name:'Progreso en dólares'})).toHaveAttribute('aria-valuenow','50');expect(screen.getByText('$75 restantes')).toBeInTheDocument();expect(screen.getByText('USD 50 restantes')).toBeInTheDocument();expect(document.querySelectorAll('.marker-car')).toHaveLength(2);expect(document.querySelector('.compact-progress')).toBeInTheDocument()})
  it('mantiene visible el 100% USD histórico con su estado terminado',()=>{render(<CurrencyProgressGroup progress={{USD:{...progress('USD',100),activeDebtCount:0}}} character="rocket"/>);expect(screen.getByRole('progressbar',{name:'Progreso en dólares'})).toHaveAttribute('aria-valuenow','100');expect(screen.getByText(/Deudas USD de este plan terminadas/)).toBeInTheDocument()})
 it('mantiene visibles ambas barras cuando ARS y USD llegan a 100%',()=>{render(<CurrencyProgressGroup progress={{ARS:{...progress('ARS',100),activeDebtCount:0},USD:{...progress('USD',100),activeDebtCount:0}}} character="dot"/>);expect(screen.getAllByRole('progressbar')).toHaveLength(2);expect(screen.getByRole('progressbar',{name:'Progreso en pesos'})).toHaveAttribute('aria-valuenow','100');expect(screen.getByRole('progressbar',{name:'Progreso en dólares'})).toHaveAttribute('aria-valuenow','100')})
})
