import { BarChart3, BookOpen, CircleDollarSign, Home, Menu, ReceiptText, Scale } from 'lucide-react'
import { useLiveQuery } from 'dexie-react-hooks'
import { NavLink, Outlet } from 'react-router-dom'
import { BRAND } from '../config/brand'
import { db } from '../storage/db'
import { todayISO } from '../utils/format'
import { QuickHelp } from './QuickHelp'
import { ReflectionCard } from './ReflectionCard'
const nav=[{to:'/plan',label:'Hoy',icon:Home},{to:'/deudas',label:'Deudas',icon:CircleDollarSign},{to:'/gastos',label:'Gastos',icon:ReceiptText},{to:'/simular',label:'Simular',icon:Scale},{to:'/progreso',label:'Progreso',icon:BarChart3},{to:'/entender',label:'Entender',icon:BookOpen},{to:'/mas',label:'Más',icon:Menu}]
export function Shell(){const settings=useLiveQuery(()=>db.settings.get('main'),[]);return <div className="app-shell"><aside className="sidebar"><NavLink to="/plan" className="brand"><span className="brand-mark">↗</span><span>{BRAND.name}</span></NavLink><nav aria-label="Navegación principal">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to}><Icon size={20}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-privacy">🔒 <strong>Tus números son tuyos.</strong><small>Se guardan en este dispositivo.</small></div></aside><main className="app-main"><MonthlyReview/>{settings?.showReflections&&<div className="shell-reflection"><ReflectionCard/></div>}<Outlet/></main><QuickHelp/><nav className="bottom-nav" aria-label="Navegación móvil">{nav.slice(0,5).map(({to,label,icon:Icon})=><NavLink key={to} to={to}><Icon size={21}/><span>{label}</span></NavLink>)}<NavLink to="/mas"><Menu size={21}/><span>Más</span></NavLink></nav></div>}
function MonthlyReview(){const settings=useLiveQuery(()=>db.settings.get('main'),[]);if(!settings?.onboardingComplete)return null;const last=settings.lastMonthlyReview?new Date(`${settings.lastMonthlyReview}T12:00:00`).getTime():0;const due=Date.now()-last>=30*86400000;if(!due)return null;const reviewed=()=>db.settings.put({...settings,lastMonthlyReview:todayISO()});return <aside className="monthly-review"><div><strong>¿Seguimos usando los mismos números?</strong><span>En Argentina cambian rápido. Revisemos lo que realmente cambió para vos.</span></div><button className="button secondary small" onClick={reviewed}>Sigue igual</button><NavLink className="button primary small" to="/gastos" onClick={reviewed}>Actualizar algunos</NavLink></aside>}
