import { z } from 'zod'
import { db, defaultSettings } from './db'
import type { BackupData } from '../types/models'

const money = z.number().finite().nonnegative()
const backupSchema = z.object({ schemaVersion:z.literal(1), exportedAt:z.string(), incomes:z.array(z.object({id:z.string(),label:z.string(),amount:money,kind:z.enum(['salary','variable','other'])})), expenses:z.array(z.object({id:z.string(),label:z.string(),amount:money,kind:z.enum(['essential','adjustable'])})), debts:z.array(z.object({ id:z.string(),name:z.string(),type:z.string(),balance:money,initialBalance:money,minimumPayment:money,agreedPayment:money.optional(),annualRate:money.optional(),cft:money.optional(),dueDate:z.string().optional(),remainingInstallments:money.optional(),creditor:z.string().optional(),notes:z.string().optional(),personalUrgency:z.number().min(1).max(5),priorityReasons:z.array(z.string()),manualOrder:z.number(),createdAt:z.string() }).passthrough()), payments:z.array(z.object({id:z.string(),debtId:z.string(),amount:money,date:z.string(),note:z.string().optional()})), snapshots:z.array(z.any()), savingsGoals:z.array(z.any()), settings:z.object({strategy:z.enum(['avalanche','snowball','personal','manual']),progressCharacter:z.enum(['runner','woman','walker','car','bike','rocket','capybara','mate','dot']),hideEncouragement:z.boolean(),reduceMotion:z.boolean(),comfortable:z.boolean(),onboardingComplete:z.boolean(),lastMonthlyReview:z.string().optional()}) })

export async function exportData(): Promise<BackupData> { const [incomes,expenses,debts,payments,snapshots,savingsGoals,stored] = await Promise.all([db.incomes.toArray(),db.expenses.toArray(),db.debts.toArray(),db.payments.toArray(),db.snapshots.toArray(),db.savingsGoals.toArray(),db.settings.get('main')]); return { schemaVersion:1, exportedAt:new Date().toISOString(), incomes,expenses,debts,payments,snapshots,savingsGoals,settings:stored ? { strategy:stored.strategy,progressCharacter:stored.progressCharacter,hideEncouragement:stored.hideEncouragement,reduceMotion:stored.reduceMotion,comfortable:stored.comfortable,onboardingComplete:stored.onboardingComplete,lastMonthlyReview:stored.lastMonthlyReview } : defaultSettings } }
export function parseBackup(raw: string) { return backupSchema.parse(JSON.parse(raw)) as BackupData }
export async function importData(data: BackupData) { await db.transaction('rw', [db.incomes,db.expenses,db.debts,db.payments,db.snapshots,db.savingsGoals,db.settings], async () => { await Promise.all([db.incomes.clear(),db.expenses.clear(),db.debts.clear(),db.payments.clear(),db.snapshots.clear(),db.savingsGoals.clear()]); await db.incomes.bulkPut(data.incomes); await db.expenses.bulkPut(data.expenses); await db.debts.bulkPut(data.debts); await db.payments.bulkPut(data.payments); await db.snapshots.bulkPut(data.snapshots); await db.savingsGoals.bulkPut(data.savingsGoals); await db.settings.put({id:'main',...data.settings}) }) }
export async function clearAllData() { await db.transaction('rw', [db.incomes,db.expenses,db.debts,db.payments,db.snapshots,db.savingsGoals,db.settings], async () => { await Promise.all([db.incomes.clear(),db.expenses.clear(),db.debts.clear(),db.payments.clear(),db.snapshots.clear(),db.savingsGoals.clear(),db.settings.clear()]); await db.settings.put({id:'main',...defaultSettings}) }) }
