import { z } from 'zod'
import { db, defaultSettings } from './db'
import type { BackupData, Debt, DebtPayment, Settings } from '../types/models'

const money=z.number().finite().nonnegative()
const debtSchema=z.object({id:z.string(),name:z.string(),type:z.enum(['credit_card','personal_loan','bank_loan','fintech_loan','mortgage','services','taxes','rent','family','friend','other']),balance:money,initialBalance:money,minimumPayment:money,agreedPayment:money.optional(),annualRate:money.optional(),cft:money.optional(),dueDate:z.string().optional(),remainingInstallments:money.optional(),creditor:z.string().optional(),notes:z.string().optional(),personalUrgency:z.number().int().min(1).max(5),priorityReasons:z.array(z.string()),manualOrder:z.number(),createdAt:z.string(),currency:z.enum(['ARS','USD']).optional(),status:z.enum(['active','paid']).optional(),paidAt:z.string().optional(),usdPaymentMethod:z.enum(['usd','ars','unknown']).optional(),conversionRate:money.positive().optional(),conversionSource:z.enum(['card','blue','manual']).optional(),conversionDate:z.string().optional(),initialConvertedBalanceARS:money.optional()})
const paymentSchema=z.object({id:z.string(),debtId:z.string(),amount:money,date:z.string(),note:z.string().optional(),currency:z.enum(['ARS','USD']).optional(),conversionRate:money.positive().optional(),amountARS:money.optional()})
const settingsSchema=z.object({strategy:z.enum(['avalanche','snowball','personal','manual']),progressCharacter:z.enum(['runner','woman','walker','car','bike','rocket','capybara','mate','dot']),hideEncouragement:z.boolean(),reduceMotion:z.boolean(),comfortable:z.boolean(),onboardingComplete:z.boolean(),lastMonthlyReview:z.string().optional(),experienceMode:z.enum(['simple','full']).optional(),showQuickHelp:z.boolean().optional(),quickHelpMinimized:z.boolean().optional(),bubblePosition:z.union([z.object({xRatio:z.number(),yRatio:z.number()}),z.object({x:z.number(),y:z.number()})]).optional(),showReflections:z.boolean().optional(),lastQuoteDate:z.string().optional(),preferredConversion:z.enum(['card','blue','manual']).optional(),manualExchangeRate:money.positive().optional(),manualExchangeReason:z.string().optional()})
const rawSchema=z.object({schemaVersion:z.union([z.literal(1),z.literal(2)]),exportedAt:z.string(),incomes:z.array(z.object({id:z.string(),label:z.string(),amount:money,kind:z.enum(['salary','variable','other'])})),expenses:z.array(z.object({id:z.string(),label:z.string(),amount:money,kind:z.enum(['essential','adjustable'])})),debts:z.array(debtSchema),payments:z.array(paymentSchema),snapshots:z.array(z.any()),savingsGoals:z.array(z.any()),settings:settingsSchema,exchangeRates:z.array(z.object({type:z.enum(['blue','card']),buy:money.positive(),sell:money.positive(),updatedAt:z.string(),fetchedAt:z.string(),provider:z.literal('DolarAPI'),source:z.enum(['DolarHoy','Ámbito Financiero'])})).optional()})
const normalizeDebt=(debt:z.infer<typeof debtSchema>):Debt=>({...debt,personalUrgency:debt.personalUrgency as Debt['personalUrgency'],currency:debt.currency??'ARS',status:debt.status??(debt.balance>0?'active':'paid')})
const normalizePayment=(payment:z.infer<typeof paymentSchema>,debts:Debt[]):DebtPayment=>({...payment,currency:payment.currency??debts.find(d=>d.id===payment.debtId)?.currency??'ARS'})
const normalizeSettings=(settings:z.infer<typeof settingsSchema>):Settings=>{const {bubblePosition,...rest}=settings,normalizedPosition=bubblePosition&&'xRatio' in bubblePosition&&bubblePosition.xRatio>=0&&bubblePosition.xRatio<=1&&bubblePosition.yRatio>=0&&bubblePosition.yRatio<=1?bubblePosition:undefined;return{...defaultSettings,...rest,bubblePosition:normalizedPosition,progressCharacter:settings.progressCharacter==='capybara'?'dot':settings.progressCharacter}}

export async function exportData():Promise<BackupData>{const[incomes,expenses,debts,payments,snapshots,savingsGoals,stored,exchangeRates]=await Promise.all([db.incomes.toArray(),db.expenses.toArray(),db.debts.toArray(),db.payments.toArray(),db.snapshots.toArray(),db.savingsGoals.toArray(),db.settings.get('main'),db.exchangeRates.toArray()]);return{schemaVersion:2,exportedAt:new Date().toISOString(),incomes,expenses,debts,payments,snapshots,savingsGoals,settings:stored?normalizeSettings(stored):defaultSettings,exchangeRates}}
export function parseBackup(raw:string):BackupData{const parsed=rawSchema.parse(JSON.parse(raw)),debts=parsed.debts.map(normalizeDebt);return{schemaVersion:2,exportedAt:parsed.exportedAt,incomes:parsed.incomes,expenses:parsed.expenses,debts,payments:parsed.payments.map(p=>normalizePayment(p,debts)),snapshots:parsed.snapshots,savingsGoals:parsed.savingsGoals,settings:normalizeSettings(parsed.settings),exchangeRates:parsed.exchangeRates??[]}}
export async function importData(data:BackupData){await db.transaction('rw',[db.incomes,db.expenses,db.debts,db.payments,db.snapshots,db.savingsGoals,db.settings,db.exchangeRates],async()=>{await Promise.all([db.incomes.clear(),db.expenses.clear(),db.debts.clear(),db.payments.clear(),db.snapshots.clear(),db.savingsGoals.clear(),db.exchangeRates.clear()]);await db.incomes.bulkPut(data.incomes);await db.expenses.bulkPut(data.expenses);await db.debts.bulkPut(data.debts);await db.payments.bulkPut(data.payments);await db.snapshots.bulkPut(data.snapshots);await db.savingsGoals.bulkPut(data.savingsGoals);await db.exchangeRates.bulkPut(data.exchangeRates);await db.settings.put({id:'main',...data.settings})})}
export async function clearAllData(){await db.transaction('rw',[db.incomes,db.expenses,db.debts,db.payments,db.snapshots,db.savingsGoals,db.settings,db.exchangeRates],async()=>{await Promise.all([db.incomes.clear(),db.expenses.clear(),db.debts.clear(),db.payments.clear(),db.snapshots.clear(),db.savingsGoals.clear(),db.settings.clear(),db.exchangeRates.clear()]);await db.settings.put({id:'main',...defaultSettings})})}
