import { describe,expect,it } from 'vitest'
import type { Currency,Debt } from '../types/models'
import { applyDebtPayment } from './payments'
import { calculateCurrencyProgress,calculateProgressByCurrency } from './currency-progress'

const debt=(id:string,currency:Currency,initialBalance:number,balance:number,conversionRate?:number):Debt=>({id,name:id,type:'other',balance,initialBalance,minimumPayment:0,personalUrgency:3,priorityReasons:[],manualOrder:0,createdAt:'2026-01-01',currency,status:balance===0?'paid':'active',...(conversionRate?{conversionRate,initialConvertedBalanceARS:initialBalance*conversionRate}:{})})

describe('progreso independiente por moneda',()=>{
  it('calcula 20% ARS y una deuda USD no cambia su denominador',()=>{const ars=[debt('A','ARS',500_000,300_000),debt('B','ARS',500_000,500_000)];expect(calculateCurrencyProgress(ars,'ARS')).toMatchObject({initialTotal:1_000_000,currentOutstanding:800_000,amountPaid:200_000,progressPercent:20});expect(calculateCurrencyProgress([...ars,debt('U','USD',10_000,1)],'ARS').progressPercent).toBe(20)})
  it('calcula 13,333% USD sin depender de referencias de conversión',()=>{const debts=[debt('A','USD',100,80,1000),debt('B','USD',50,50,5000)];const result=calculateCurrencyProgress(debts,'USD');expect(result).toMatchObject({initialTotal:150,currentOutstanding:130,amountPaid:20});expect(result.progressPercent).toBeCloseTo(13.333333,5)})
  it.each([1000,5000,500,2199.99,1])('mantiene ARS 25% y USD 50% con cotización %s',rate=>{const debts=[debt('A','ARS',1_000_000,750_000),debt('U','USD',100,50,rate)];expect(calculateCurrencyProgress(debts,'ARS').progressPercent).toBe(25);expect(calculateCurrencyProgress(debts,'USD').progressPercent).toBe(50)})
  it('un pago ARS solo mueve ARS y un pago USD solo mueve USD',()=>{const debts=[debt('A','ARS',1_000_000,750_000),debt('U','USD',100,50)];const usdBefore=calculateCurrencyProgress(debts,'USD').progressPercent;debts[0]=applyDebtPayment(debts[0],100_000,'2026-09-01').debt;expect(calculateCurrencyProgress(debts,'ARS').progressPercent).toBe(35);expect(calculateCurrencyProgress(debts,'USD').progressPercent).toBe(usdBefore);const arsBefore=calculateCurrencyProgress(debts,'ARS').progressPercent;debts[1]=applyDebtPayment(debts[1],10,'2026-09-01').debt;expect(calculateCurrencyProgress(debts,'USD').progressPercent).toBe(60);expect(calculateCurrencyProgress(debts,'ARS').progressPercent).toBe(arsBefore)})
  it('agregar una deuda de otra moneda nunca altera el progreso existente',()=>{const ars=debt('A','ARS',1000,500),usd=debt('U','USD',100,25);const arsBefore=calculateCurrencyProgress([ars],'ARS'),usdBefore=calculateCurrencyProgress([usd],'USD');expect(calculateCurrencyProgress([ars,usd],'ARS')).toEqual(arsBefore);expect(calculateCurrencyProgress([usd,ars],'USD')).toEqual(usdBefore)})
  it('conserva una deuda USD pagada y muestra exactamente 100%',()=>{const result=calculateCurrencyProgress([debt('U','USD',100,0)],'USD');expect(result.progressRatio).toBe(1);expect(result.progressPercent).toBe(100);expect(result.activeDebtCount).toBe(0)})
  it('cerrar todas las deudas deja ambas monedas exactamente en 100%',()=>{const debts=[debt('A','ARS',1000,0),debt('U','USD',100,0)];const result=calculateProgressByCurrency(debts);expect(result.ARS?.progressPercent).toBe(100);expect(result.USD?.progressPercent).toBe(100)})
  it('al agregar deuda después de 100% recalcula el denominador de esa moneda',()=>{const result=calculateCurrencyProgress([debt('U1','USD',100,0),debt('U2','USD',100,100)],'USD');expect(result).toMatchObject({initialTotal:200,currentOutstanding:100,amountPaid:100,progressPercent:50})})
  it('el wrapper omite monedas que nunca formaron parte del plan',()=>{expect(calculateProgressByCurrency([debt('A','ARS',100,50)])).toEqual({ARS:expect.objectContaining({progressPercent:50})});expect(calculateProgressByCurrency([debt('U','USD',100,50)])).toEqual({USD:expect.objectContaining({progressPercent:50})})})
})
