import type { Debt,StrategyKind } from '../types/models'
import { allowsExtraPayment,monthlyObligation } from './installments'
export type ProjectionStatus='projected'|'no_capacity'|'indeterminate'|'extreme_duration'
export interface ProjectionMonth{month:number;date:string;payments:Record<string,number>;balances:Record<string,number>;interest:number}
export interface Projection{strategy:StrategyKind;status:ProjectionStatus;months?:number;payoffDate?:string;remainingBalance:number;reason?:string;totalPaid:number;estimatedInterest:number|null;completionDate:string|null;firstCompletedDebtId?:string;schedule:ProjectionMonth[];approximate:boolean;stalled:boolean}
export interface ProjectionOptions{mandatoryAffordable?:boolean;safetyLimit?:number}
const safe=(value:number)=>Number.isFinite(value)?Math.max(0,value):0
const factor=(debt:Debt)=>debt.currency==='USD'?(debt.conversionRate??0):1
const addMonths=(start:Date,count:number)=>{const date=new Date(start);date.setUTCMonth(date.getUTCMonth()+count);return Number.isFinite(date.getTime())?date.toISOString().slice(0,10):null}
export function orderDebts(debts:Debt[],strategy:StrategyKind):Debt[]{return[...debts.filter(debt=>debt.status!=='paid'&&debt.balance>0)].sort((a,b)=>strategy==='avalanche'?(b.annualRate??-1)-(a.annualRate??-1)||a.balance-b.balance:strategy==='snowball'?a.balance-b.balance:strategy==='personal'?b.personalUrgency-a.personalUrgency||a.balance-b.balance:a.manualOrder-b.manualOrder)}
const done=(base:Omit<Projection,'stalled'>):Projection=>({...base,stalled:base.status==='no_capacity'||base.status==='indeterminate'})
export function projectDebts(debts:Debt[],monthlyExtra:number,strategy:StrategyKind,startDate=new Date(),maxMonths=1200,options:ProjectionOptions={}):Projection{
 const source=debts.filter(debt=>debt.status!=='paid'&&safe(debt.balance)>0)
 if(!source.length){const date=addMonths(startDate,0);return done({strategy,status:'projected',months:0,payoffDate:date??undefined,remainingBalance:0,totalPaid:0,estimatedInterest:0,completionDate:date,schedule:[],approximate:false})}
 const initialRemaining=source.reduce((sum,debt)=>sum+safe(debt.balance)*factor(debt),0),unknownRates=source.some(debt=>debt.annualRate===undefined)
 if(!Number.isFinite(monthlyExtra)||monthlyExtra<0||!Number.isFinite(startDate.getTime()))return done({strategy,status:'indeterminate',remainingBalance:initialRemaining,reason:'Los valores de la proyección no son válidos.',totalPaid:0,estimatedInterest:null,completionDate:null,schedule:[],approximate:true})
 if(source.some(debt=>debt.currency==='USD'&&factor(debt)<=0))return done({strategy,status:'indeterminate',remainingBalance:source.reduce((sum,debt)=>sum+safe(debt.balance),0),reason:'Falta una referencia bloqueada para proyectar una deuda en USD.',totalPaid:0,estimatedInterest:null,completionDate:null,schedule:[],approximate:true})
 const active=source.map(debt=>{const conversion=factor(debt);return debt.currency==='USD'?{...debt,balance:debt.balance*conversion,initialBalance:debt.initialBalance*conversion,minimumPayment:debt.minimumPayment*conversion,agreedPayment:debt.agreedPayment===undefined?undefined:debt.agreedPayment*conversion,installmentAmount:debt.installmentAmount===undefined?undefined:debt.installmentAmount*conversion,currency:'ARS' as const}:{...debt}})
 if(options.mandatoryAffordable===false)return done({strategy,status:'no_capacity',remainingBalance:initialRemaining,reason:'Con estos números no hay margen para cubrir todos los compromisos este mes.',totalPaid:0,estimatedInterest:unknownRates?null:0,completionDate:null,schedule:[],approximate:unknownRates})
 if(monthlyExtra===0&&active.every(debt=>monthlyObligation(debt)<=0))return done({strategy,status:'no_capacity',remainingBalance:initialRemaining,reason:'No hay una capacidad de pago mensual cargada.',totalPaid:0,estimatedInterest:unknownRates?null:0,completionDate:null,schedule:[],approximate:unknownRates})
 const balances=new Map(active.map(debt=>[debt.id,debt.balance])),installments=new Map(active.map(debt=>[debt.id,debt.remainingInstallments])),obligationBudgets=new Map(active.map(debt=>[debt.id,monthlyObligation(debt)]));let totalPaid=0,totalInterest=0,firstCompletedDebtId:string|undefined;const schedule:ProjectionMonth[]=[],limit=Math.max(1,Math.min(12000,Math.floor(options.safetyLimit??maxMonths)))
 for(let month=1;month<=limit;month++){let extra=monthlyExtra,monthInterest=0;const payments:Record<string,number>={},beforeMonth=[...balances.values()].reduce((sum,value)=>sum+Math.max(0,value),0)
  for(const debt of active){const balance=balances.get(debt.id)??0;if(balance<=0)continue;const interest=balance*safe(debt.annualRate??0)/1200;if(!Number.isFinite(interest))return done({strategy,status:'indeterminate',remainingBalance:balance,reason:'La tasa produce un resultado fuera de rango.',totalPaid,estimatedInterest:null,completionDate:null,firstCompletedDebtId,schedule,approximate:true});balances.set(debt.id,balance+interest);monthInterest+=interest;totalInterest+=interest}
  for(const debt of active){const balance=balances.get(debt.id)??0,budgeted=obligationBudgets.get(debt.id)??0;if(balance<=0){extra+=budgeted;continue}const left=installments.get(debt.id),obligation=left===0?0:Math.min(balance,budgeted),paid=Math.min(balance,obligation);balances.set(debt.id,balance-paid);payments[debt.id]=(payments[debt.id]??0)+paid;totalPaid+=paid;extra+=Math.max(0,budgeted-paid);if(left!==undefined&&paid>0)installments.set(debt.id,Math.max(0,left-1))}
  const ordered=orderDebts(active.map(debt=>({...debt,balance:balances.get(debt.id)??0})),strategy)
  for(const debt of ordered){if(extra<=0)break;if(!allowsExtraPayment(debt))continue;const balance=balances.get(debt.id)??0;if(balance<=0)continue;const paid=Math.min(balance,extra);balances.set(debt.id,balance-paid);payments[debt.id]=(payments[debt.id]??0)+paid;totalPaid+=paid;extra-=paid}
  for(const debt of ordered)if(!firstCompletedDebtId&&(balances.get(debt.id)??0)<=.005)firstCompletedDebtId=debt.id
  const monthBalances=Object.fromEntries(active.map(debt=>[debt.id,Math.max(0,balances.get(debt.id)??0)])),remaining=Object.values(monthBalances).reduce((sum,value)=>sum+value,0);schedule.push({month,date:addMonths(startDate,month)??'',payments,balances:monthBalances,interest:monthInterest})
  if(remaining<=.005){const payoffDate=addMonths(startDate,month)??undefined;return done({strategy,status:'projected',months:month,payoffDate,remainingBalance:0,totalPaid,estimatedInterest:unknownRates?null:totalInterest,completionDate:payoffDate??null,firstCompletedDebtId,schedule,approximate:unknownRates})}
  if(remaining>=beforeMonth-.005)return done({strategy,status:'indeterminate',remainingBalance:remaining,reason:'Los pagos cargados no reducen el capital con estas tasas.',totalPaid,estimatedInterest:unknownRates?null:totalInterest,completionDate:null,firstCompletedDebtId,schedule,approximate:unknownRates})
 }
 const remaining=[...balances.values()].reduce((sum,value)=>sum+Math.max(0,value),0),window=schedule.slice(-12),windowStart=window[0]?Object.values(window[0].balances).reduce((sum,value)=>sum+value,0):initialRemaining,reduced=Math.max(0,windowStart-remaining),perMonth=window.length>1?reduced/(window.length-1):0,linear=active.every(debt=>(debt.annualRate??0)===0),estimated=linear&&perMonth>0?limit+Math.ceil(remaining/perMonth):undefined
 if(reduced>0)return done({strategy,status:'extreme_duration',months:estimated&&Number.isFinite(estimated)?estimated:undefined,remainingBalance:remaining,reason:'Con los valores actuales, este plan no tiene una fecha práctica de finalización.',totalPaid,estimatedInterest:unknownRates?null:totalInterest,completionDate:null,firstCompletedDebtId,schedule,approximate:unknownRates})
 return done({strategy,status:'indeterminate',remainingBalance:remaining,reason:'No se pudo determinar una finalización con los datos actuales.',totalPaid,estimatedInterest:unknownRates?null:totalInterest,completionDate:null,firstCompletedDebtId,schedule,approximate:unknownRates})
}
