import { describe, expect, it } from 'vitest'
import { calculateBudget, calculatePortfolioProgress, formatProgressPercent, mandatoryPayment, orderDebts, projectDebts, reductionImpact } from '.'
import type { Debt } from '../types/models'

const debt=(overrides:Partial<Debt>={}):Debt=>({id:'a',name:'Visa',type:'credit_card',balance:100000,initialBalance:100000,minimumPayment:10000,personalUrgency:3,priorityReasons:[],manualOrder:0,createdAt:'2026-01-01',currency:'ARS',status:'active',...overrides})
describe('financial engine',()=>{
  it('reserva esenciales y obligaciones antes del extra',()=>{expect(calculateBudget([{id:'i',label:'Sueldo',amount:800000,kind:'salary'}],[{id:'e',label:'Casa',amount:480000,kind:'essential'}],[debt({minimumPayment:190000,balance:500000})])).toMatchObject({availableExtra:130000,deficit:0})})
  it('detecta déficit sin sugerir extra',()=>{expect(calculateBudget([{id:'i',label:'Sueldo',amount:100,kind:'salary'}],[{id:'e',label:'Casa',amount:80,kind:'essential'}],[debt({balance:50,minimumPayment:30})])).toMatchObject({availableExtra:0,deficit:10})})
  it('limita el mínimo al saldo y contempla cuota pactada',()=>{expect(mandatoryPayment(debt({balance:5000,minimumPayment:10000}))).toBe(5000);expect(mandatoryPayment(debt({minimumPayment:1000,agreedPayment:3000}))).toBe(3000)})
  it('ordena avalancha, nieve, personal y manual',()=>{const ds=[debt({id:'a',balance:50,annualRate:10,personalUrgency:5,manualOrder:2}),debt({id:'b',balance:20,annualRate:80,personalUrgency:1,manualOrder:1})];expect(orderDebts(ds,'avalanche')[0].id).toBe('b');expect(orderDebts(ds,'snowball')[0].id).toBe('b');expect(orderDebts(ds,'personal')[0].id).toBe('a');expect(orderDebts(ds,'manual')[0].id).toBe('b')})
  it('proyecta interés cero y deuda ya pagada',()=>{expect(projectDebts([debt({balance:100,initialBalance:100,minimumPayment:0,annualRate:0})],100,'snowball').months).toBe(1);expect(projectDebts([debt({balance:0})],100,'snowball').months).toBe(0)})
  it('marca como aproximado si falta tasa y no inventa intereses',()=>{const result=projectDebts([debt()],10000,'snowball');expect(result.approximate).toBe(true);expect(result.estimatedInterest).toBeNull()})
  it('no produce NaN con números grandes',()=>{const result=projectDebts([debt({balance:1e12,initialBalance:1e12,minimumPayment:1e11,annualRate:20})],1e11,'avalanche');expect(Number.isFinite(result.totalPaid)).toBe(true)})
  it('calcula progreso y evita negativos',()=>{expect(calculatePortfolioProgress([debt({initialBalance:100,balance:60})])).toMatchObject({initialTotal:100,currentOutstanding:60,totalPaidPrincipal:40,progressPercent:40,method:'native'})})
  it.each([[100,100,0],[100,99.5,.5],[100,99,1],[100,62,38],[100,1,99],[100,0,100]])('muestra progreso exacto de %s a %s', (initial,balance,percent)=>expect(calculatePortfolioProgress([debt({initialBalance:initial,balance,status:balance===0?'paid':'active'})]).progressPercent).toBe(percent))
  it('una deuda nueva actualiza honestamente el denominador',()=>expect(calculatePortfolioProgress([debt({id:'a',initialBalance:100,balance:50}),debt({id:'b',initialBalance:100,balance:100})]).progressPercent).toBe(25))
  it('progreso USD depende del saldo USD y no de la cotización',()=>{const before=calculatePortfolioProgress([debt({currency:'USD',initialBalance:50,balance:30,conversionRate:1900})]),after=calculatePortfolioProgress([debt({currency:'USD',initialBalance:50,balance:30,conversionRate:2200})]);expect(before.progressPercent).toBe(40);expect(after.progressPercent).toBe(40)})
  it('cartera mixta usa referencias iniciales bloqueadas',()=>{const result=calculatePortfolioProgress([debt({currency:'ARS',initialBalance:100000,balance:50000}),debt({id:'u',currency:'USD',initialBalance:100,balance:50,initialConvertedBalanceARS:200000})]);expect(result).toMatchObject({progressPercent:50,method:'locked_ars'})})
  it('formatea microprogreso sin esconderlo',()=>{expect(formatProgressPercent(.5)).toBe('0,5%');expect(formatProgressPercent(1)).toBe('1%');expect(formatProgressPercent(38.4)).toBe('38,4%');expect(formatProgressPercent(100)).toBe('100%')})
  it('un recorte nunca alarga el plan',()=>{const result=reductionImpact(10000,[debt({annualRate:0})],10000,'snowball');expect(result.changed.months!).toBeLessThanOrEqual(result.base.months!)})
})
