import { describe,expect,it } from 'vitest'
import type { Debt,DebtPayment,ExperienceMode,Settings } from '../types/models'
import { applyDebtPayment,createPaymentRecord } from './payments'
import { calculatePortfolioProgress } from './portfolio-progress'
import { changeExperienceMode } from '../services/experience-mode'
import { defaultSettings } from '../storage/db'

const debt=(id:string,initialBalance:number,balance=initialBalance,changes:Partial<Debt>={}):Debt=>({id,name:id,type:'other',initialBalance,balance,minimumPayment:0,personalUrgency:3,priorityReasons:[],manualOrder:0,createdAt:'2026-01-01',currency:'ARS',status:balance===0?'paid':'active',...changes})
const pay=(debts:Debt[],payments:DebtPayment[],id:string,amount:number)=>{const index=debts.findIndex(item=>item.id===id),result=applyDebtPayment(debts[index],amount,'2026-09-01');debts[index]=result.debt;payments.push(createPaymentRecord(debts[index],result.paymentAmount,'2026-09-01',`p${payments.length}`))}
const expectProgress=(debts:Debt[],payments:DebtPayment[],initial:number,outstanding:number,paid:number,percent:number)=>expect(calculatePortfolioProgress(debts,payments)).toMatchObject({initialTotal:initial,currentOutstanding:outstanding,totalPaidPrincipal:paid,progressPercent:percent})

describe('progreso global de cartera',()=>{
  it('reproduce la regresión con pagos repartidos en tres deudas',()=>{const debts=[debt('Visa',1_000_000),debt('Master',500_000),debt('Amigo',250_000)],payments:DebtPayment[]=[];expectProgress(debts,payments,1_750_000,1_750_000,0,0);pay(debts,payments,'Visa',200_000);expectProgress(debts,payments,1_750_000,1_550_000,200_000,200_000/1_750_000*100);pay(debts,payments,'Master',100_000);expectProgress(debts,payments,1_750_000,1_450_000,300_000,300_000/1_750_000*100);pay(debts,payments,'Amigo',250_000);expectProgress(debts,payments,1_750_000,1_200_000,550_000,550_000/1_750_000*100);pay(debts,payments,'Master',400_000);expectProgress(debts,payments,1_750_000,800_000,950_000,950_000/1_750_000*100);pay(debts,payments,'Visa',800_000);expectProgress(debts,payments,1_750_000,0,1_750_000,100)})
  it.each([1,2,5])('suma las %i deudas completas',count=>{const debts=Array.from({length:count},(_,i)=>debt(String(i),100,50));expectProgress(debts,[],count*100,count*50,count*50,50)})
  it('mantiene pagadas y activas dentro del denominador',()=>expectProgress([debt('a',100,0),debt('b',100,80)],[],200,80,120,60))
  it('agregar y borrar una deuda actualiza toda la cartera',()=>{const debts=[debt('a',100,50)];expectProgress(debts,[],100,50,50,50);debts.push(debt('b',100));expectProgress(debts,[],200,150,50,25);debts.splice(0,1);expectProgress(debts,[],100,100,0,0)})
  it('USD es estable aunque cambie la cotización actual',()=>{const before=calculatePortfolioProgress([debt('u',100,60,{currency:'USD',conversionRate:1000})]),after=calculatePortfolioProgress([debt('u',100,60,{currency:'USD',conversionRate:3000})]);expect(before.progressPercent).toBe(40);expect(after.progressPercent).toBe(40)})
  it('mezcla ARS/USD con referencias iniciales bloqueadas',()=>{const result=calculatePortfolioProgress([debt('a',100_000,50_000),debt('u',100,25,{currency:'USD',initialConvertedBalanceARS:200_000})]);expect(result).toMatchObject({initialTotal:300_000,currentOutstanding:100_000,method:'locked_ars'});expect(result.progressPercent).toBeCloseTo(200/3,10)})
})

describe('transiciones de experiencia',()=>{const switchMode=(settings:Settings,mode:ExperienceMode,debts:Debt[],payments:DebtPayment[])=>({settings:changeExperienceMode(settings,mode),debts,payments});it('Simple a Completo conserva pagos anteriores y acepta pagos posteriores',()=>{const debts=[debt('a',100_000)],payments:DebtPayment[]=[];pay(debts,payments,'a',20_000);const result=switchMode({...defaultSettings,experienceMode:'simple'},'full',debts,payments);expect(result.debts[0].balance).toBe(80_000);expect(result.payments).toHaveLength(1);expect(calculatePortfolioProgress(result.debts,result.payments).progressPercent).toBe(20);pay(result.debts,result.payments,'a',30_000);expect(result.payments).toHaveLength(2);expect(calculatePortfolioProgress(result.debts,result.payments).progressPercent).toBe(50)});it('Completo a Simple conserva una segunda deuda y da 10%',()=>{const debts=[debt('a',100_000,80_000),debt('b',100_000)],result=switchMode({...defaultSettings,experienceMode:'full'},'simple',debts,[]);expect(result.debts).toHaveLength(2);expect(calculatePortfolioProgress(result.debts).progressPercent).toBe(10)});it('diez alternancias no cambian ningún dato financiero',()=>{const debts=[debt('a',100,70)],payments=[createPaymentRecord(debt('a',100,70),30,'2026-09-01','p')],snapshot=JSON.stringify({debts,payments});let settings:Settings={...defaultSettings,experienceMode:'simple'};for(let index=0;index<10;index++)settings=changeExperienceMode(settings,index%2?'simple':'full');expect(JSON.stringify({debts,payments})).toBe(snapshot);expect(settings.experienceMode).toBe('simple')})})
